### ISSUE TITLE
validate criterion is not defined

### ISSUE THREAD

**Issue by huizhang0110** [thudzj/NSA#1]
Hi, @thudzj 

Congratulations on your great work on NIPS2020!
But I meet a name error when running this repository, specifically, the name `criterion` for validation is not defined. 

![image](https://user-images.githubusercontent.com/32508847/102858484-526a0e80-4465-11eb-9043-811ad9e8f4f8.png)

**Comment by thudzj** [comment]
Thank you~ Indeed there are some typos, I have fixed them, so hopefully, I will close this issue.
